name: Github Page Publish
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'test/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: package-lock.json

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm sdk build
          pnpm sdk build:docs
          pnpm build:examples
          pnpm sdk build:ghpages

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/sdk/ghpages
          enable_jekyll: false
